In [1]:
import numpy as np


In [6]:
a=np.array([[1,2,3],[2,5,6],[6,7,4]])
print ("Matrix:\n", a)

Matrix:
 [[1 2 3]
 [2 5 6]
 [6 7 4]]


In [8]:
b=np.eye(5)
print("I:\n",b)

I:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [9]:
c=np.ones((7,5))
print("Ones:\n",c)

Ones:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [12]:
d = np.arange(0,32,4)
print (d)

[ 0  4  8 12 16 20 24 28]


In [14]:
e = d.reshape((4,2))
print (e)

[[ 0  4]
 [ 8 12]
 [16 20]
 [24 28]]


In [16]:
a=np.array([1,2,3])
b=np.array([[1],[2],[3]])
print(a)
print(b)

[1 2 3]
[[1]
 [2]
 [3]]


In [17]:
a = np.array([[1, 0], [0, 1]])
b = np.array([[4, 1], [2, 2]])
r1 = np.dot(a, b)
r2 = a.dot(b)

In [18]:
print("Size a",a.shape)

Size a (2, 2)


In [1]:
print(" multiplication_1",r1)
print(" multiplication_2",r2)

NameError: name 'r1' is not defined

In [3]:
import numpy as np
a=np.array([[1,1],[1,2]])
print(a)

[[1 1]
 [1 2]]


In [6]:
b=np.linalg.inv(a)
print(b)

[[ 2. -1.]
 [-1.  1.]]


In [8]:
 a = np.eye(4, 5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]
